apiVersion: v1
kind: Pod
metadata:
  name: grasshopper-pod
  labels:
    app: grasshopper
spec:
  serviceAccountName: grasshopper-sa
  imagePullSecrets:
    - name: regcred
  nodeSelector:
    kubernetes.io/hostname: master-node
  containers:
    - name: grasshopper
      image: quintenlauwaert/kubernetes-images:gh-v3
      imagePullPolicy: Always   
      command: ["python3", "code/main_operator.py"]
      args: ["--mode", "PLS"]
      envFrom:
        - secretRef:
            name: grasshopper-openstack-creds
      volumeMounts:
        - name: nfs-share
          mountPath: /mnt/nfs_share
  volumes:
    - name: nfs-share
      persistentVolumeClaim:
        claimName: nfs-pvc
  restartPolicy: Never
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
