apiVersion: v1
kind: Pod
metadata:
  name: grasshopper-watcher
  labels:
    app: grasshopper
spec:
  serviceAccountName: grasshopper-sa
  nodeSelector:
    kubernetes.io/hostname: worker
  containers:
    - name: grasshopper
      image: grasshopper:v2
      imagePullPolicy: Never     
      command: ["python3", "main.py"]
      args: ["--mode", "PLS"]
      envFrom:
        - secretRef:
            name: grasshopper-openstack-creds
  restartPolicy: Never
