apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scaler
  template:
    metadata:
      labels:
        task: monitoring
        app: scaler
    spec:
      containers:
      - name: scaler
        image: decomads/scaler
        imagePullPolicy: Always
        volumeMounts:
        - name: kubeconfig
          mountPath: /root/.kube
      volumes:
      - name: kubeconfig
        secret:
          secretName: kubeconfig
