apiVersion: v1
kind: Pod
metadata:
  name: pod2
  namespace: default
  labels:
    app: nginx
    role: dev
spec:
  nodeName: worker-5
  containers:
  - image: ''
    name: user4
    ports:
    - containerPort: 8080
      protocol: http
