apiVersion: v1
kind: Pod
metadata:
  name: grasshopper-operator-v2-on-master
  labels:
    app: grasshopper
spec:
  serviceAccountName: grasshopper-sa
  nodeSelector:
    kubernetes.io/hostname: master
  containers:
    - name: grasshopper
      image: grasshopper:v2
      imagePullPolicy: Never     
      command: ["python3", "main_operator.py"]
      args: ["--mode", "PLS"]
      envFrom:
        - secretRef:
            name: grasshopper-openstack-creds
  restartPolicy: Never
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
