apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/mnt/nfs_share"  # Path where the NFS share is located on the machine.
    server: "172.23.24.63"  # IP-address of NFS Server.