
version: "1.2.0"

persistenceReplicas: 1
persistenceCpu: 500m
persistenceMemory: 1000Mi

webuiReplicas: 1
webuiCpu: 500m
webuiMemory: 1000Mi

recommenderReplicas: 1
recommenderCpu: 500m
recommenderMemory: 1000Mi

registryReplicas: 1
registryCpu: 500m
registryMemory: 1000Mi

dbReplicas: 1
dbCpu: 500m
dbMemory: 1000Mi

authReplicas: 1
authCpu: 500m
authMemory: 1000Mi


imageReplicas: 1
imageCpu: 500m
imageMemory: 1000Mi


image:
  pullPolicy: IfNotPresent
