apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: teastore-policy
  namespace: teastore
spec:
  podSelector:
    matchLabels:
      run: teastore-locust
  policyTypes:
  - Egress
  - Ingress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          role: admin
    - podSelector:
        matchLabels:
          app: teastore
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: teastore
